name: Build Firmware

on: 
  release:
    types: [published]
  push:
    branches: 
      - master
      - duchenpaul-action-1
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        pip install esphome

    # - name: Build
    #   run: |
    #     cd openwrt
    #     echo -e "$(nproc) thread build."
    #     make -j$(nproc) V=s

    # - name: Build
    #   run: |
    #     cd openwrt
    #     echo -e "$(nproc) thread build."
    #     make -j$(nproc) V=s

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
